### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by AKuHAK** [AKuHAK/PS2Ident#2]
@sp193 I just would like to warn you that your sources for PC side utilities (which use Visual Studio code) are leaking some of your personal information. Probably you don't care, but you can easily remove from sources such files:
- *.sdf
- *.suo
- *.ipch
- *.aps
- *.filters
- *.user

**Comment by sp193** [comment]
Hi. Thanks for the heads up. I think it is okay to have those files around - my name remains found on the Internet anyway. I believe PS2Ident has a clean purpose too, so I don't mind being affiliated with it.
