### ISSUE TITLE
Freezes at loading screen

### ISSUE THREAD

**Issue by ab310714gz4700** [AKuHAK/PS2Ident#8]
I'm sure that my USB drive is formatted to FAT32, not exFAT

**Comment by J013k** [comment]
I can confirm (version 470cf77).
It stuck at this screen:
![https://i.postimg.cc/05C6X6BZ/reere.png](https://i.postimg.cc/05C6X6BZ/reere.png)

**Comment by ab310714gz4700** [comment]
I tried copying to memory card but it's stuck at loading screen!

**Comment by ab310714gz4700** [comment]
https://github.com/AKuHAK/PS2Ident/actions/runs/9809003789

This artifact is expired

**Comment by ab310714gz4700** [comment]
Fixed in two commits!
https://github.com/AKuHAK/PS2Ident/actions/runs/12122406893
https://github.com/AKuHAK/PS2Ident/actions/runs/12123340479

**Comment by ab310714gz4700** [comment]
The recent one is this link:
https://github.com/AKuHAK/PS2Ident/actions/runs/12123340479
